package secure;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Dimension;
import java.awt.List;
import java.awt.Toolkit;
import java.awt.Window;
import java.util.ArrayList;
import java.util.Vector;
import javafx.scene.control.CheckBox;
import javax.swing.JCheckBox;
import java.awt.MenuBar;
import javax.swing.JFrame;

/**
 * GUI interface using the design feature of the Netbeans
 *
 * @author Liigah
 */
public class Adoption_Form extends javax.swing.JFrame {

    /**
     * Creates new form Adoption_Form
     */
    public Adoption_Form() {
        initComponents();
        this.setLocationRelativeTo(null);
        centeredFrame(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jLabelAdoptionForm = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextWelcomeMessage = new javax.swing.JTextArea();
        jLabelWhatAnimal = new javax.swing.JLabel();
        jLabelAge = new javax.swing.JLabel();
        jCheckBoxLess1yr = new javax.swing.JCheckBox();
        jCheckBox3yrs = new javax.swing.JCheckBox();
        jCheckBox5yrs = new javax.swing.JCheckBox();
        jCheckBox10yrs = new javax.swing.JCheckBox();
        jCheckBoxDog = new javax.swing.JCheckBox();
        jCheckBoxCat = new javax.swing.JCheckBox();
        jCheckBoxBunny = new javax.swing.JCheckBox();
        jCheckBoxTortoise = new javax.swing.JCheckBox();
        jCheckBoxSnake = new javax.swing.JCheckBox();
        jCheckBox15yrs = new javax.swing.JCheckBox();
        jLabelSize = new javax.swing.JLabel();
        jCheckBox5kg = new javax.swing.JCheckBox();
        jCheckBox10kg = new javax.swing.JCheckBox();
        jCheckBox15kg = new javax.swing.JCheckBox();
        jCheckBox25kg = new javax.swing.JCheckBox();
        jCheckBox35kg = new javax.swing.JCheckBox();
        jCheckBox50kg = new javax.swing.JCheckBox();
        jCheckBoxAgreement = new javax.swing.JCheckBox();
        jButtonSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelAdoptionForm.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelAdoptionForm.setForeground(new java.awt.Color(0, 102, 0));
        jLabelAdoptionForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAdoptionForm.setText("Adoption Form");
        getContentPane().add(jLabelAdoptionForm);
        jLabelAdoptionForm.setBounds(229, 20, 236, 34);

        jTextWelcomeMessage.setBackground(new java.awt.Color(204, 255, 204));
        jTextWelcomeMessage.setColumns(20);
        jTextWelcomeMessage.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextWelcomeMessage.setRows(5);
        jTextWelcomeMessage.setText("Welcome to our Animal Shelter! \nWe are happy to see that you are considering adopting an animal. However, before you start browsing\nand/or applying for an adoption, please make sure that you are ready to take care of an animal and are \nsure that it is what you want.\nREMEMBER! A pet is not a toy and you have the responsibility to take care of your pet!\n");
        jScrollPane1.setViewportView(jTextWelcomeMessage);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(25, 60, 642, 120);

        jLabelWhatAnimal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelWhatAnimal.setText("What kind of animal do you want to adopt?");
        getContentPane().add(jLabelWhatAnimal);
        jLabelWhatAnimal.setBounds(40, 204, 280, 23);

        jLabelAge.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelAge.setText("Prefered Age?");
        getContentPane().add(jLabelAge);
        jLabelAge.setBounds(40, 296, 245, 22);

        jCheckBoxLess1yr.setText(" < 1 year ");
        getContentPane().add(jCheckBoxLess1yr);
        jCheckBoxLess1yr.setBounds(356, 297, 90, 23);

        jCheckBox3yrs.setText("> 3 years");
        getContentPane().add(jCheckBox3yrs);
        jCheckBox3yrs.setBounds(468, 297, 80, 23);

        jCheckBox5yrs.setText(" > 5 years");
        getContentPane().add(jCheckBox5yrs);
        jCheckBox5yrs.setBounds(567, 297, 75, 23);

        jCheckBox10yrs.setText("> 10 years");
        getContentPane().add(jCheckBox10yrs);
        jCheckBox10yrs.setBounds(356, 338, 90, 23);

        jCheckBoxDog.setText("Dog");
        getContentPane().add(jCheckBoxDog);
        jCheckBoxDog.setBounds(356, 205, 70, 23);

        jCheckBoxCat.setText("Cat");
        getContentPane().add(jCheckBoxCat);
        jCheckBoxCat.setBounds(356, 246, 70, 23);

        jCheckBoxBunny.setText("Bunny");
        getContentPane().add(jCheckBoxBunny);
        jCheckBoxBunny.setBounds(468, 205, 80, 23);

        jCheckBoxTortoise.setText("Tortoise");
        getContentPane().add(jCheckBoxTortoise);
        jCheckBoxTortoise.setBounds(567, 205, 80, 23);

        jCheckBoxSnake.setText("Snake");
        getContentPane().add(jCheckBoxSnake);
        jCheckBoxSnake.setBounds(468, 246, 81, 23);

        jCheckBox15yrs.setText("> 15 years");
        getContentPane().add(jCheckBox15yrs);
        jCheckBox15yrs.setBounds(468, 338, 80, 23);

        jLabelSize.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelSize.setText("Prefered Size?");
        getContentPane().add(jLabelSize);
        jLabelSize.setBounds(40, 379, 223, 25);

        jCheckBox5kg.setText("> 5 kg");
        getContentPane().add(jCheckBox5kg);
        jCheckBox5kg.setBounds(356, 381, 90, 23);

        jCheckBox10kg.setText(">10 kg");
        getContentPane().add(jCheckBox10kg);
        jCheckBox10kg.setBounds(468, 381, 80, 23);

        jCheckBox15kg.setText(">15 kg");
        getContentPane().add(jCheckBox15kg);
        jCheckBox15kg.setBounds(565, 381, 80, 23);

        jCheckBox25kg.setText(">25 kg");
        getContentPane().add(jCheckBox25kg);
        jCheckBox25kg.setBounds(356, 422, 90, 23);

        jCheckBox35kg.setText("> 35 kg");
        getContentPane().add(jCheckBox35kg);
        jCheckBox35kg.setBounds(468, 422, 80, 23);

        jCheckBox50kg.setText("> 45 kg");
        getContentPane().add(jCheckBox50kg);
        jCheckBox50kg.setBounds(565, 422, 80, 23);

        jCheckBoxAgreement.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jCheckBoxAgreement.setText("I agree to the Animal Shelter´s terms and conditions. ");
        getContentPane().add(jCheckBoxAgreement);
        jCheckBoxAgreement.setBounds(40, 469, 310, 25);

        jButtonSubmit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonSubmit.setForeground(new java.awt.Color(51, 153, 0));
        jButtonSubmit.setText("SUBMIT");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSubmit);
        jButtonSubmit.setBounds(460, 496, 148, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secure/animals (3).JPG"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 570);

        setBounds(0, 0, 710, 603);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * method that calls for the next JFrame
     *
     * @param evt
     */
    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        new Submission().setVisible(true); //when you press the Submit button, the Submission JFrame pops up
        this.dispose();
    }//GEN-LAST:event_jButtonSubmitActionPerformed
    public void centeredFrame(javax.swing.JFrame objFrame) {
        Dimension objDimension = Toolkit.getDefaultToolkit().getScreenSize();
        int iCoordX = (objDimension.width - objFrame.getWidth()) / 2;
        int iCoordY = (objDimension.height - objFrame.getHeight()) / 2;
        objFrame.setLocation(iCoordX, iCoordY);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adoption_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adoption_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adoption_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adoption_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                Adoption_Form af = new Adoption_Form();
                af.setBounds(0, 0, 700, 590);
                af.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JCheckBox jCheckBox10kg;
    private javax.swing.JCheckBox jCheckBox10yrs;
    private javax.swing.JCheckBox jCheckBox15kg;
    private javax.swing.JCheckBox jCheckBox15yrs;
    private javax.swing.JCheckBox jCheckBox25kg;
    private javax.swing.JCheckBox jCheckBox35kg;
    private javax.swing.JCheckBox jCheckBox3yrs;
    private javax.swing.JCheckBox jCheckBox50kg;
    private javax.swing.JCheckBox jCheckBox5kg;
    private javax.swing.JCheckBox jCheckBox5yrs;
    private javax.swing.JCheckBox jCheckBoxAgreement;
    private javax.swing.JCheckBox jCheckBoxBunny;
    private javax.swing.JCheckBox jCheckBoxCat;
    private javax.swing.JCheckBox jCheckBoxDog;
    private javax.swing.JCheckBox jCheckBoxLess1yr;
    private javax.swing.JCheckBox jCheckBoxSnake;
    private javax.swing.JCheckBox jCheckBoxTortoise;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAdoptionForm;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelSize;
    private javax.swing.JLabel jLabelWhatAnimal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextWelcomeMessage;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables

}
