package secure;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 * GUI interface using the design feature of Netbeans
 *
 * @author Liigah
 */
public class Submission extends javax.swing.JFrame {

    /**
     * Creates new form Submission
     */
    public Submission() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSubmission = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelSubmission.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelSubmission.setForeground(new java.awt.Color(0, 102, 0));
        jLabelSubmission.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSubmission.setText("Thank you for your adoption submission!");
        getContentPane().add(jLabelSubmission);
        jLabelSubmission.setBounds(100, 40, 465, 73);

        jButtonExit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(0, 102, 0));
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit);
        jButtonExit.setBounds(40, 461, 103, 35);

        jLabelMessage.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelMessage.setForeground(new java.awt.Color(0, 102, 0));
        jLabelMessage.setText("We will get back to you shortly and discuss ");
        getContentPane().add(jLabelMessage);
        jLabelMessage.setBounds(160, 120, 360, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("the next steps of the adoption process.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 160, 330, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secure/animals (3).JPG"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 570);

        setBounds(0, 0, 714, 612);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Submission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Submission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Submission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Submission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                Submission af = new Submission();
                af.setBounds(0, 0, 700, 590);
                af.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelSubmission;
    // End of variables declaration//GEN-END:variables

    private void CenteredFrame(Submission aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
