/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secure;


/**
 *
 * @author Liigah
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFirstName = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        txtPass = new javax.swing.JLabel();
        txtConfirmPass = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        txtLastName = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        txtRegistration = new javax.swing.JLabel();
        txtRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        txtFirstName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(0, 102, 0));
        txtFirstName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtFirstName.setText("First Name");
        getContentPane().add(txtFirstName);
        txtFirstName.setBounds(10, 56, 63, 17);

        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 102, 0));
        txtEmail.setText("E-mail Address *");
        getContentPane().add(txtEmail);
        txtEmail.setBounds(10, 184, 97, 17);

        txtPass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtPass.setForeground(new java.awt.Color(0, 102, 0));
        txtPass.setText("Password");
        getContentPane().add(txtPass);
        txtPass.setBounds(10, 249, 56, 17);

        txtConfirmPass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtConfirmPass.setForeground(new java.awt.Color(0, 102, 0));
        txtConfirmPass.setText("Confirm Password");
        getContentPane().add(txtConfirmPass);
        txtConfirmPass.setBounds(10, 315, 107, 17);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(20, 79, 219, 31);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(20, 144, 219, 31);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(20, 207, 219, 31);

        txtLastName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(0, 102, 0));
        txtLastName.setText("Last Name");
        getContentPane().add(txtLastName);
        txtLastName.setBounds(10, 121, 61, 17);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(16, 272, 223, 32);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(16, 338, 223, 32);

        txtRegistration.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtRegistration.setForeground(new java.awt.Color(0, 102, 0));
        txtRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRegistration.setText("Registration");
        getContentPane().add(txtRegistration);
        txtRegistration.setBounds(53, 19, 135, 26);

        txtRegister.setBackground(new java.awt.Color(102, 153, 0));
        txtRegister.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtRegister.setForeground(new java.awt.Color(255, 255, 255));
        txtRegister.setText("Register");
        txtRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(txtRegister);
        txtRegister.setBounds(80, 400, 95, 31);

        setBounds(0, 0, 269, 507);
    }// </editor-fold>//GEN-END:initComponents

    private void txtRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegisterActionPerformed
      
    }//GEN-LAST:event_txtRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel txtConfirmPass;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtFirstName;
    private javax.swing.JLabel txtLastName;
    private javax.swing.JLabel txtPass;
    private javax.swing.JButton txtRegister;
    private javax.swing.JLabel txtRegistration;
    // End of variables declaration//GEN-END:variables
}
